name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Java Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Analyse de la qualité avec SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Crée la clé du projet en remplaçant '/' par '_'
          PROJECT_KEY=$(echo "${GITHUB_REPOSITORY}" | sed 's/\//_/')
          echo "Project key: $PROJECT_KEY"
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$PROJECT_KEY \
            -Dsonar.login=$SONAR_TOKEN
