name: Documentation Java

on:
  pull_request:
    types: [closed]

jobs:
  build-docs:
    name: Génération et déploiement de la documentation
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Générer Javadoc
        run: mvn -B javadoc:javadoc

      - name: Déployer documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
